applications:
- application_id: b5a62305726c54a3
  collection_points:
  - collection_point_id: 95205be01f9985d0
    cp_details:
      app_id: b5a62305726c54a3
      cp_id: 95205be01f9985d0
      org_id: 0f167779270f5c3b
      org_key: qhg1uuj3-E4wYB0YhsXT1Q
      org_secret: RSPkY4klF4DyavxJvCBjwtY8cpcBey-0F0t_YjAlTko
      registered_at: '2024-07-15 10:23:06.989524'
  - collection_point_id: 81b6c6c4cf747af6
    cp_details:
      app_id: b5a62305726c54a3
      cp_id: 81b6c6c4cf747af6
      org_id: 0f167779270f5c3b
      org_key: qhg1uuj3-E4wYB0YhsXT1Q
      org_secret: RSPkY4klF4DyavxJvCBjwtY8cpcBey-0F0t_YjAlTko
      registered_at: '2024-07-15 10:23:09.581431'
  - collection_point_id: ea82e1b62a6a5bff
    cp_details:
      app_id: b5a62305726c54a3
      cp_id: ea82e1b62a6a5bff
      org_id: 0f167779270f5c3b
      org_key: qhg1uuj3-E4wYB0YhsXT1Q
      org_secret: RSPkY4klF4DyavxJvCBjwtY8cpcBey-0F0t_YjAlTko
      registered_at: '2024-07-15 10:23:17.456460'
  type: mobile
version: '1.0'
