applications:
- application_id: a2fb9896684b886c
  collection_points:
  - collection_point_id: 8711cd7a9c2dc423
    cp_details:
      _id: 6694e05a32d2725351a48014
        state: !!binary |
          ZpTgWjLSclNRpIAU
      app_id: a2fb9896684b886c
      cp_id: 8711cd7a9c2dc423
      org_id: 5d00d632a57cf451
      org_key: IeHxxj-Pi2NSg9XlTW7b_w
      org_secret: uBYdkNDL9LNyvrCL1-7mY3tH3PrOoFLJe3M0k51Es8I
      registered_at: 2024-07-15 08:39:54.662500
  type: mobile
version: '1.0'
