
# Do `go build -o app .` first 

# Production stage
FROM debian

RUN apt update && apt install -y ca-certificates

# Create a directory for the application
RUN mkdir /concur-backend

# Create a directory for the log file
RUN mkdir /concur-backend/logs


# Copy the built binary from the build stage
COPY ./app /concur-backend/app






# Set the working directory
WORKDIR /concur-backend

# Expose port
EXPOSE 8080

# Run the Golang application
CMD ["./app"]